### ISSUE TITLE
Key bindings on Mac do not work

### ISSUE THREAD

**Issue by komape** [DeepLcom/deepl-tui#2]
The key bindings described in the Readme are not working on a Mac. I tried multiple combinations of the keys 'option', 'control', and 'command' in order to replace 'alt' but none is working.

How do key bindings work on a Mac?

**Comment by cluttrdev** [comment]
Hi @komape, does the `ctrl-q` key binding work, i.e. does it quit the application?

**Comment by komape** [comment]
> Hi @komape, does the `ctrl-q` key binding work, i.e. does it quit the application?

Yes, that works.

**Comment by cluttrdev** [comment]
Okay, working on it. It's just a bit tricky because I don't have a Mac available to directly test changes on.

**Comment by cluttrdev** [comment]
Hi, sorry for the delay...
Can you check how the terminal app you're using is configured to handle the `option` key?
Maybe it's set to use it as the `meta` key, see e.g. [here](https://superuser.com/questions/496090/how-to-use-alt-commands-in-a-terminal-on-os-x).

**Comment by komape** [comment]
> Can you check how the terminal app you're using is configured to handle the `option` key?

Checked it and the option `Use Option as Meta key` was not checked. Ticking the box makes the key shortcuts work. Thanks a lot!
